### ISSUE TITLE
Browser does work

### ISSUE THREAD

**Issue by xieve** [basti564/Oculess#1]
Hi, first of all: thanks for the great utility! Just wanted to point out that the browser does actually still work, it's just the shortcut in the home menu that doesn't. When you exit ALVR, it opens the dashboard in the browser, which works just fine and actually can be used as a workaround. I think it should be possible to create a new shortcut, maybe just a stub apk? Further, this could also mean that TV still works, I haven't tried it yet, but it'd be nice for streaming VR movies I guess.

Edit: I [think I found the relevant line](https://github.com/alvr-org/ALVR/blob/d50a5551fc5f3e812a12b3b9fc6dd2977ee024ca/alvr/client/android/app/src/main/java/com/polygraphene/alvr/OvrActivity.java#L398)

**Comment by basti564** [comment]
Thanks, I didn't think that the internal browser works. I have been using the Firefox VR browser while logged out. Maybe I will add opening the Browser as a feature to this app :) I have been able to to locate a few hidden ways to launch some system internal apps while reverse engineering the vrshell and other system apps. I could include a "system app launcher", but that will probably take some time until it's implemented.

Have a nice day!
Bastian

**Comment by xieve** [comment]
Yeah, [here's a quick and dirty stub/launcher I created](https://github.com/basti564/Oculess/files/6185622/com.xieve.oculusbrowserlauncher.zip), there's probably a better way to implement this. After creating that I found Firefox VR, which is probably the better choice anyway. As such this is not an issue to me anymore, you can close this if you want or keep it as something for the future.

**Comment by basti564** [comment]
@xieve I can't open the link you have sent me, but I made my own launcher. You should be able to open a browser by choosing "BROWSER" from the dropdown list and then clicking on "GO"
https://github.com/basti564/vrLauncher/releases/tag/v1.0

Have a nice day!
Bastian

**Comment by dzg** [comment]
Any way to set Firefox as the default browser to open links from in-game?

**Comment by basti564** [comment]
@dzg I have no idea, but I'm not even sure if Firefox VR can accept opening links, as that's normally not needed.

**Comment by xieve** [comment]
Opening a link from another application will work with Firefox VR. If you
want the Oculus Browser, just uninstall Firefox temporarily, open any link
and select the Oculus Browser, then reinstall Firefox.
