### ISSUE TITLE
Can't talk in new update in discord

### ISSUE THREAD

**Issue by JasonHyde9** [basti564/Oculess#103]
In quest 2 with background sound on (all permissions correct) oculess seems to be having problems letting me talk. It was crashing a lot for some reason, I can now hear others but they can't hear me when in a game. Ever since I wiped my quest and downloaded updated oculess and discord there has been a lot of problems. I've tried 5+ different earlier versions of discord.

**Comment by threethan** [comment]
If you can hear others, the background audio service is working. Apps can actually record audio in the background without any modifications.
I've had the same problem before, though not consistently. Try re-opening discord while in game (no need to restart the call) and see if that fixes it. There _might_ be also be issues if another app (such as the game) is using the mic.

**Comment by JasonHyde9** [comment]
> If you can hear others, the background audio service is working. Apps can actually record audio in the background without any modifications. I've had the same problem before, though not consistently. Try re-opening discord while in game (no need to restart the call) and see if that fixes it. There _might_ be also be issues if another app (such as the game) is using the mic.

Any other ideas? I can't talk in the game either, no idea whats happening.

**Comment by threethan** [comment]
Check that no other sideloaded apps are attempting to use the mic, and that the mic is not disabled in the quick settings panel.
I'm going to close this issue, since Oculess doesn't do anything to effect audio recording, it can only effect audio playback.
