### ISSUE TITLE
[Feature Request] disable Explore (or at least it automatically showing on startup)

### ISSUE THREAD

**Issue by AAGaming00** [basti564/Oculess#109]
trying to disable it with `pm disable` yields `java.lang.SecurityException: Shell cannot change component state for com.oculus.explore/null to 2`
However, pm uninstall --user 0 works, but then the store page for Explore loads on startup instead.

**Comment by threethan** [comment]
For some reason, you can't do it through shell, but can in the settings. Try using a third-party launcher such as [this](https://github.com/threethan/LightningLauncher/) to open the android settings app (not the same as the Quest settings app!) and then navigate to apps -> Explore. You can disable it there.

**Comment by AAGaming00** [comment]
> For some reason, you can't do it through shell, but can in the settings. Try using a third-party launcher such as [this](https://github.com/threethan/LightningLauncher/) to open the android settings app (not the same as the Quest settings app!) and then navigate to apps -> Explore. You can disable it there.

Yes, but then wouldn't it open the store to the Explore app listing on startup instead? that's what happens when I uninstall --user 0 it

**Comment by threethan** [comment]
It does not, at least for me.

**Comment by AAGaming00** [comment]
Seems to work fine, yeah. Thanks!
