### ISSUE TITLE
Cannot remove device-owner/uninstall Oculess anymore

### ISSUE THREAD

**Issue by Bluscream** [basti564/Oculess#111]
After clicking on "Accounts" (https://github.com/basti564/Oculess#make-oculess-a-device-owner) the quest just shows a empty settings screen?

[https://cdn-cf-east.streamable.com/video/mp4/p5os7m.mp4?Expires=1698643380&Signature=azjfr~bOfwF02yIUzGj7Fzo0gPq3LM8IKo7E1nSfauSUmZVUGDe37C8N0-VQKtH0mNV-oEg-W3F5znSEzXTfkm8VNpAt8pQUF~X0kSoJELtkkB4bYUI8GYBS3DC~P-ogzmWlxj8i2Cq4i0iFr~7RYBifAi48Nz20-n9v0WBb384yFCUHpZ81uWQ9J4VHMCSV~h9Ffqn6edeyIuAlG3AYQAuuLeFZ2SGH3hoET0~yMWieU7yfBCH0j8sYP29okPQHMR3ErwJxLVqCVMKheE72eTvDSZg23EdPHXu49OzLR~6NuRkZFgD1Z4T4SJl9NY5xP1Eer~SAbIblc8fGFKRx9Q__&Key-Pair-Id=APKAIEYUVEN4EVB2OKEQ](https://cdn-cf-east.streamable.com/video/mp4/p5os7m.mp4?Expires=1698643380&Signature=azjfr~bOfwF02yIUzGj7Fzo0gPq3LM8IKo7E1nSfauSUmZVUGDe37C8N0-VQKtH0mNV-oEg-W3F5znSEzXTfkm8VNpAt8pQUF~X0kSoJELtkkB4bYUI8GYBS3DC~P-ogzmWlxj8i2Cq4i0iFr~7RYBifAi48Nz20-n9v0WBb384yFCUHpZ81uWQ9J4VHMCSV~h9Ffqn6edeyIuAlG3AYQAuuLeFZ2SGH3hoET0~yMWieU7yfBCH0j8sYP29okPQHMR3ErwJxLVqCVMKheE72eTvDSZg23EdPHXu49OzLR~6NuRkZFgD1Z4T4SJl9NY5xP1Eer~SAbIblc8fGFKRx9Q__&Key-Pair-Id=APKAIEYUVEN4EVB2OKEQ)

**Comment by restorerootfs** [comment]
Please read the README.
If the "Remove/Check Accounts" button brings you to an empty settings page try the following ADB command to get to the Settings app and manually navigate to the Accounts section. adb shell "monkey -p com.android.settings -c android.intent.category.LAUNCHER 1"

**Comment by Bluscream** [comment]
The readme was updated after i had the issue, but i have sold the headset so it doesn't matter anymore. Thanks anyway.
