### ISSUE TITLE
I'm confused on how to uninstall

### ISSUE THREAD

**Issue by TheTechWiz5305** [basti564/Oculess#119]
I saw this part but wasn't sure what it meant.

![image](https://github.com/basti564/Oculess/assets/132825368/9a7a7633-ecce-499a-ba2c-e6e99685ee6c)

I want to uninstall it because my headset says in settings something about the device being managed by an admin, and I can't change some settings I want to change. So are there any guides to uninstall?

**Comment by threethan** [comment]
Open it and select "Remove Device Owner"
