### ISSUE TITLE
Add Feedback after Disabling Telemetry

### ISSUE THREAD

**Issue by Ratismal** [basti564/Oculess#16]
Hi,

First of all, thank you for this! Telemetry has been my biggest issue and concern with getting a Quest, and this solves my problem. I really appreciate the time and effort that's been put into this!

Would it be possible to get some sort of feedback on whether or not disabling telemetry was a success, or if telemetry is currently disabled?

From what I understand in the code, you're taking certain services that Facebook uses for telemetry and hiding them (which renders them unusable until unhidden). Using `DevicePolicyManager#isApplicationHidden`, we could query which of the services are currently hidden and display a status to the user:
- Disabled (all services hidden)
- Partially Disabled (some services hidden)
- Enabled (no services hidden)

Adding this simple addition would make Oculess a lot more user-friendly, and give users confidence that telemetry is actually disabled. I'm no expert on android or Kotlin, but if you think this is something worth having but aren't willing to devote time to it, I could take a crack at it myself. Just let me know!

Thank you for your time, and thanks again for making this awesome app!

**Comment by basti564** [comment]
Yes, I'm planning to have the ability for users to choose which packages to disable in the next release and viewing which ones are currently disabled is a part of that. I'm already doing that for the "disable updates" option which turns into a "enable updates" button after disabeling.

**Comment by raykai** [comment]
Can't wait for this to be implemented!
For the time being, Is there an ADB command we can run to be sure the telemetry is off?

**Comment by GHOSCHT** [comment]
You can test if it's working by seeing if the packages still "exist". Try the following command "adb shell pm path com.oculus.unifiedtelemetry", but for all the following packages: "com.oculus.unifiedtelemetry", "com.oculus.gatekeeperservice", "com.oculus.notification_proxy", "com.oculus.bugreporter", "com.oculus.os.logcollector", "com.oculus.appsafety".
If you don't get a response it works. If you get back a path it doesn't.

I still recommend blocking the following domains oculus.com oculuscdn.com facebook-hardware.com facebook.net facebook.com fbcdn.com fbsbx.com fbcdn.net fb.me fb.com crashlytics.com You can test blocking graph.facebook.com and graph.oculus.com too, but that might break some apps :/

_Originally posted by @basti564 in https://github.com/basti564/Oculess/issues/3#issuecomment-819137822_

**Comment by basti564** [comment]
The latest commit 1f2df2f5b2f19f8b639f7e87fd8841b1295d039e now shows feedback on the success of disabling telemetry. A signed apk can be obtained from [here](https://github.com/basti564/Oculess/releases/tag/v1.3.1).
