### ISSUE TITLE
Oculess breaks custom home environments

### ISSUE THREAD

**Issue by arthurrasmusson** [basti564/Oculess#17]
Right away - THANKS FOR MAKING OCULESS! I've been wanting something like this for a long time.

Right, to the bug now. I found that initially after installing Oculess my custom home environment worked fine (just a black void). Since then it's gone away and reverted back to the default Oculus home environment. I've also noted that the menu which allows you to select your home environment appears not to work anymore.

There's a community focused on developing these custom home environments here:
https://discord.gg/fY2aD9B

I don't think many of them are using Oculess yet - I'd like to help close this bug but I'm not sure where to start.

**Comment by Ruqen** [comment]
Updates?

**Comment by threethan** [comment]
This is an old issue, and I've used custom homes alongside Oculess with no issue. Assuming this is resolved.
