### ISSUE TITLE
Cannot disable Companion Server Admin

### ISSUE THREAD

**Issue by OXERY** [basti564/Oculess#23]
Hi & thx for this great app!

Just wanted to "free" my Quest 1 from Facebook, but I cannot disable the Companion Server Admin. When clicking the toggle, I only get a white "app screen" without any text. (unlike https://youtu.be/aSokYzpB1D8?t=280) .. do you have any ideas on that? I rebooted the Quest, but nothing changed.

**Comment by basti564** [comment]
Yes, you need to change your system theme to light mode. The text colours are messed up in dark mode and text doesn't display

**Comment by basti564** [comment]
I added a note to the readme in e518794665c776992f440ee4845e0cc22e37b1c0

**Comment by ReallyRad** [comment]
Having same problem with v1.3.3 and v1.2.
Unfortunately wasn't able to switch to light mode as the option is missing from experimental features.

**Comment by basti564** [comment]
@ReallyRad 
> Unfortunately wasn't able to switch to light mode as the option is missing from experimental features.

You can sideload [Settings Shortcut](https://github.com/basti564/SettingsShortcut/releases/) and navigate to Display>Dark Theme and then turn it off from there

**Comment by ReallyRad** [comment]
Thanks! That did the trick.
