### ISSUE TITLE
Multi-Account and Library Sharing not working

### ISSUE THREAD

**Issue by fahrstuhl** [basti564/Oculess#24]
I disabled telemetry using Oculess and can't add another Oculus account on my Quest 2, neither using the account settings on the Quest, nor using the account manager in Oculus Developer Hub. In another issue @basti564 mentioned [multi-account might cause problems](https://github.com/basti564/Oculess/issues/22#issuecomment-989963681). Is there a way to disable telemetry and still get multi-account working?

**Comment by threethan** [comment]
Telemetry can be disabled through the posted ADB commands.

As for multi account, new users can be added via android settings. (Sideload settings shortcut)
Unsure about library sharing.
