### ISSUE TITLE
Oculess with Oculus Go

### ISSUE THREAD

**Issue by moocow1452** [basti564/Oculess#25]
I understand that Oculus is designed for the Quest platform, but if you attempt to disable the companion on Oculus Go, it boots you out of Home and makes it completely unable to operate, giving a three dot loading animation in a black void, and the Oculus Go control. I understand if it's completely out of scope, but if there's any suggestions you would have or troubleshooting you would want me to do, I'm ready to help.

**Comment by basti564** [comment]
I don’t think Oculess is easily portable to the Go, making a CFW without telemetry would make more sense imo, which has nothing to do with Oculess.
