### ISSUE TITLE
Light Mode setting no longer exists

### ISSUE THREAD

**Issue by gergles** [basti564/Oculess#28]
I recently purchased a new Quest 2 and have Oculess installed, but when I attempt to disable the device owner, the white screen appears. I see in the instructions to enable light mode, but this does not appear to be possible - the option does not exist in experimental settings on my device (my Quest updated to v37 during setup.)

Is there a workaround/ADB command/etc. that can be run to change the device owner instead?

**Comment by basti564** [comment]
It's not in the experimental options. I think it's in the personalization settings.

**Comment by alec-calhoun** [comment]
Stuck in the same boat and nope. It's not in personalization settings. The option to change to light theme appears to be removed.
Perhaps changing Oculess for dark mode or giving us a guide for doing it blind would help

**Comment by basti564** [comment]
> Is there a workaround/ADB command/etc. that can be run to change the device owner instead?
Also note, that you don't need to disable the companion server to enable the Device Owner

**Comment by basti564** [comment]
Update, light mode is now located in Settings>System>Display for some reason
