### ISSUE TITLE
Installing CA / User certificates

### ISSUE THREAD

**Issue by mmavx** [basti564/Oculess#29]
If Oculess is set as a device owner, would it be possible to install custom certificates with the app,
or is there something blocking it or making it useless I don't know about?

e.g. with https://developer.android.com/reference/android/app/admin/DevicePolicyManager#installCaCert(android.content.ComponentName,%20byte[]) or `installKeyPair`

If it works it would be great to have that feature in Oculess!

**Comment by basti564** [comment]
I don't think it would be of much use as other apps won't trust the added CA.
> Inserted user CAs aren't automatically trusted by apps in Android 7.0 (API level 24) and higher.
