### ISSUE TITLE
verify if working?

### ISSUE THREAD

**Issue by dzg** [basti564/Oculess#3]
Not an issue ... but a question.

First, thanks for this awesome tool!

Is there a way to verify it's working by, say, checking DNS logs? I still see a lot of traffic to `graph.oculus.com`, `graph.facebook.com`, etc ... but that might be unrelated to telemetry.

Thanks

**Comment by basti564** [comment]
You can test if it's working by seeing if the packages still "exist". Try the following command "adb shell pm path com.oculus.unifiedtelemetry", but for all the following packages: "com.oculus.unifiedtelemetry", "com.oculus.gatekeeperservice", "com.oculus.notification_proxy", "com.oculus.bugreporter", "com.oculus.os.logcollector", "com.oculus.appsafety".
If you don't get a response it works. If you get back a path it doesn't.

I still recommend blocking the following domains oculus.com oculuscdn.com facebook-hardware.com facebook.net facebook.com fbcdn.com fbsbx.com fbcdn.net fb.me fb.com crashlytics.com You can test blocking graph.facebook.com and graph.oculus.com too, but that might break some apps :/

**Comment by seascape** [comment]
Thank you for this wonderful app.

May I ask what blocking your additional recommended domains might help with? And is there any way to do that besides at the router level / pihole?

**Comment by basti564** [comment]
> Thank you for this wonderful app.
> 
> 
> 
> May I ask what blocking your additional recommended domains might help with? And is there any way to do that besides at the router level / Pi-hole?

I'm sorry for the late reply. Blocking the additional domains is just in case something breaks (for example disabling app safety doesn't work right now) or Facebook updates something. Blocking it with a pi-hole would be the simplest and most effective way.It might be possible to host sour own DNS server on the Quest, but idk if it's worth it to do that.

**Comment by raykai** [comment]
btw a good alternative to pi-hole is Adguard Home as you can run it on a windows os :)  https://github.com/AdguardTeam/AdguardHome

**Comment by basti564** [comment]
Yeah, Adguard Home should also work :)
