### ISSUE TITLE
Light mode no longer available

### ISSUE THREAD

**Issue by alec-calhoun** [basti564/Oculess#30]
The option to change themes to light mode no longer exists. I've checked everywhere in settings. It's not in experimental or personalization.
Perhaps add support for dark mode or a guide for us to disable the companion blind?

**Comment by basti564** [comment]
The setting seems to be now in Settings>System>Display

**Comment by Ninsto** [comment]
This is still an issue but I just did my one with dark mode on, just watch the tutorial video and click based on where he clicks in the video. You'll know you clicked the right spot when it says "You will be signed out of oculus.com" or something along those lines.

**Comment by basti564** [comment]
I took the time to make an [app that opens Android System Settings](https://github.com/basti564/SettingsShortcut/releases/) which you can use to enable Light mode, just sideload and open it and then navigate to Display>Dark Theme and turn it off
