### ISSUE TITLE
cant set device owner trough-adb shell dpm set-device-owner com.bos.oculess/.DevAdminReceiver

### ISSUE THREAD

**Issue by ilco3** [basti564/Oculess#32]
the adb comand keeps failing -even after removing all fb acounts .the adb comand keeps failing

here are my logs from sidequest

Error: Command failed: "C:\Users\ilco\AppData\Roaming\SideQuest\platform-tools\adb.exe" -s 1WMHH865E71212 shell dpm set-device-owner com.bos.oculess/.DevAdminReceiver java.lang.IllegalStateException: Not allowed to set the device owner because there are already some accounts on the device at android.os.Parcel.createException(Parcel.java:2046) at android.os.Parcel.readException(Parcel.java:2006) at android.os.Parcel.readException(Parcel.java:1954) at android.app.admin.IDevicePolicyManager$Stub$Proxy.setDeviceOwner(IDevicePolicyManager.java:8392) at com.android.commands.dpm.Dpm.runSetDeviceOwner(Dpm.java:203) at com.android.commands.dpm.Dpm.onRun(Dpm.java:115) at com.android.internal.os.BaseCommand.run(BaseCommand.java:65) at com.android.internal.os.BaseCommand.run(BaseCommand.java:49) at com.android.commands.dpm.Dpm.main(Dpm.java:41) at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method) at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:338) Caused by: android.os.RemoteException: Remote stack trace: at com.android.server.devicepolicy.DevicePolicyManagerService.enforceCanSetDeviceOwnerLocked(DevicePolicyManagerService.java:8653) at com.android.server.devicepolicy.DevicePolicyManagerService.setDeviceOwner(DevicePolicyManagerService.java:7822) at android.app.admin.IDevicePolicyManager$Stub.onTransact(IDevicePolicyManager.java:3270) at android.os.Binder.execTransactInternal(Binder.java:1021) at android.os.Binder.execTransact(Binder.java:994)

**Comment by TheKing349** [comment]
Did you find a fix for this? I'm having the same issue...

**Comment by TheKing349** [comment]
So I figured it out, if you have multiple accounts on your Oculus, not just the ones on Oculess, but if you actually ADDED an account besides yours, you'll have to remove that account...

**Comment by basti564** [comment]
> So I figured it out, if you have multiple accounts on your Oculus, not just the ones on Oculess, but if you actually ADDED an account besides yours, you'll have to remove that account...

Yes, Multiple Accounts will break the adb command. Btw. a factory reset will fix it if this doesn't work.
