### ISSUE TITLE
[Feature Requests] Adding a light dimmer button. 

### ISSUE THREAD

**Issue by Goldenfreddy0703** [basti564/Oculess#34]
Hey there, sorry for bothering you but Oculess is a great app and I'm very happy to use it for background music and stuff but I was wondering if it's possible to dim the lights in the oculus environments. 

Backthen when oculus tv was good, you could launch your own 3rd party apps on oculus tv and the lights around you would go dark or dim. Ever sense oculus tv updated, they removed the dim feature when launching an app and they remove the ability to launch 3rd party apps and that eliminated controller input support which sucks so I was wondering if it's possible to have a button to dim the lights out like how oculus tv would do it. 

If it is possible, that would be great and thanks for hearing me out.

**Comment by basti564** [comment]
Hmm, I’ve looked into it and it doesn’t seem possible to do that. The closest thing would be to mod a 2d app into 3D and add a custom dark environment, but that would need to be done for every app and the dimming function isn’t something that fits in with the other features.

**Comment by Goldenfreddy0703** [comment]
Aww ok thank you. Guess I'm going to have to modify the kodi app for this feature for playback then. Thank you very much for answering my feature request.
