### ISSUE TITLE
No accounts listed in the remove accounts section

### ISSUE THREAD

**Issue by lolpippiou** [basti564/Oculess#35]
The title should be self explanatory, there's absolutely nothing but the sync toggle when trying to remove my accounts

**Comment by basti564** [comment]
The v38 PTC release doesn't have the account section (anymore)

**Comment by lolpippiou** [comment]
Oh, so if I leave the PTC will it come back or nah?

**Comment by juan-yunis** [comment]
No, once you update, it can't be rolled back :(.
@basti564 this means Oculess is useless in v38? or is there any workaround?

**Comment by basti564** [comment]
@juan-yunis Oculess still works perfectly on the v38 PTC, there just isn't a public way to set up Device Owners on the current PTC release/beta. I will update the setup steps if the account section doesn't return in the official release of v38, but until then setup on beta versions isn't supported.

**Comment by juan-yunis** [comment]
@basti564 but let me understand, all Oculess features rely on the ability to remove all the accounts in order to make Oculess app a Device Owner right?, so for now in v38 PTC there is no way to use those features because of the inability to remove accounts.
When you said "there just isn't a public way to set up Device Owners", you meant there is another way to do it so? or waiting for official v38 is the only way?

Thanks for your answer!

**Comment by basti564** [comment]
@juan-yunis The Device Owner only needs to be set up once, if you have already enabled it on a stable (non PTC) version you will still be able to use it after you update to the v38 PTC. Yes, there are other [private] ways to set up Oculess as Device Owner without needing to delete Accounts and that work on v38, but they have other drawbacks and most people would probably mess up their Quest somehow. The "remove accounts" function itself is already a "hack" to setup a Device Owner on the Quest and it just doesn't make sense to release a new method for every beta version, when it is worse and different from the stable firmware release pretty much everyone is on.

**Comment by basti564** [comment]
The account section has been added back in the latest v38 version (24721900433100000)

**Comment by lolpippiou** [comment]
les go
