### ISSUE TITLE
[Feature Request] Option to toggle guardian

### ISSUE THREAD

**Issue by Timocop** [basti564/Oculess#36]
Sometimes its useful to disable the guardian if you want to leave your playspace without triggering passthrough.
For example if you play in an indefinite playspace or playspace which is bigger than the Quest allows.
(Or when your bed is behind the Guardian and you just want to lay down in VR)
Normally this setting can be changed in the developer settings (Settings > System > Developer).

However, when disabling oculus companion you wont fine the developer settings anymore to toggle the guardian.
Right now its only possible with SideQuest USB/wireless ADB settings when oculus companion is disabled. 
Would be nice to see this somehow being added in the app (without loosing focus from the active app would be optimal).

**Comment by basti564** [comment]
I don't believe this is possible and Facebook would directly patch it if they found out about it. Third-party apps should never be able to disable system safety features and if you ever find a way for a third-party app to disable guardian I would recommend you to just report it to Facebook and claim the $3k bounty for it. (see the 4th from last example in the [hardware payout guidelines](https://www.facebook.com/whitehat/payout_guidelines/hardware))

**Comment by Timocop** [comment]
Why would that not be possible? The SideQuest app uses an adb command to enable/disable Guardian remotely.

![2022-03-06_18-00-24](https://user-images.githubusercontent.com/22834512/156933476-bceaddbf-f8c2-4793-bf66-be86299e0759.png)

**Comment by basti564** [comment]
> Why would that not be possible? The SideQuest app uses an adb command to enable/disable Guardian remotely.
> 
> ![2022-03-06_18-00-24](https://user-images.githubusercontent.com/22834512/156933476-bceaddbf-f8c2-4793-bf66-be86299e0759.png)

As you said it requires access to the android development bridge and a computer which has to be explicitly enabled. An app being able to disable safety features would be extremely worrying and able to cause physical harm, which means Facebook would immediately patch it once they figure out how it works. I will see if there is a way to open the official settings panel to turn off Guardian, but a function to directly enable it will never be implemented.

**Comment by D3SOX** [comment]
Maybe this could work in a similar way to LADB:
https://play.google.com/store/apps/details?id=com.draco.ladb
https://github.com/tytydraco/ladb

**Comment by basti564** [comment]
> Maybe this could work in a similar way to LADB:
> https://play.google.com/store/apps/details?id=com.draco.ladb
> https://github.com/tytydraco/ladb

The problem with wireless ADB on Android 10 is that you need ADB to enable it every time you restart. Also you can just use any terminal emulator with wireless ADB to connect to the Quest itself to disable guardian if you're okay with enabling it every reboot and don't need Oculess for that.

**Comment by D3SOX** [comment]
I personally don't need this right now (because I have the Oculus Companion still enabled), but I can understand @Timocop's request here. I also disable the guardian when playing Beat Saber via the settings developer section
