### ISSUE TITLE
[Feature Request] Make App "testOnly" for ownership removal via ADB

### ISSUE THREAD

**Issue by MisutaaAsriel** [basti564/Oculess#37]
According to [https://stackoverflow.com/questions/49128293/how-to-remove-set-device-owner-in-android-dpm](https://stackoverflow.com/questions/49128293/how-to-remove-set-device-owner-in-android-dpm) & [https://snow.dog/blog/kiosk-mode-android](https://snow.dog/blog/kiosk-mode-android). if `<application>` includes the property `android:testOnly="true"`, then the application's device administration can be **removed** using ADB via `adb shell dpm remove-active-admin [package]/[adminReceiver]` without factory reset.

_Normally_, recommendations are to _remove_ this property for production deployment, as typical device administrator apps are used for MDM, and as such should not be user-removable. However, for Oculess' purposes, this is **rather the opposite**.

In theory, this would mean, if this property were set in the Oculess package manifest, users would no longer require a factory reset to remove device ownership. Instead, `adb shell dpm remove-active-admin com.bos.oculess/.DevAdminReceiver` would be enough to remove ownership of oculess, as easy as it was to add it.

e.g. as part of [AndroidManifest.xml](https://github.com/basti564/Oculess/blob/main/app/src/main/AndroidManifest.xml):
```xml
...

<application
        android:allowBackup="true"
        android:banner="@mipmap/ic_banner"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/Theme.Oculess"
        android:testOnly="true"> <!-- Note added property on this line -->

...
```
Would this be something worth testing and confirming? If so, it saves users the headache of having to reset.

**Comment by basti564** [comment]
The remove-active-admin doesn't seem to work on the Quest even with a testOnly device owner

**Comment by MisutaaAsriel** [comment]
Ah. That is quite the shame. I suppose yet another behavioral modification to the system by Oculus/Meta. 😕
