### ISSUE TITLE
Cannot switch to light theme

### ISSUE THREAD

**Issue by Michael775433** [basti564/Oculess#42]
Since v38 march 2022 update I can no longer set light theme the shortcut for settings no longer works

**Comment by basti564** [comment]
Why doesn't the Settings Shortcut work? I'm on v39 and it works.
It could be that the background of the Settings look transparent, but it should still work.

**Comment by Michael775433** [comment]
Ok I will try it again
Btw. Thank you for making this great app your work is outstanding

**Comment by Michael775433** [comment]
Thank you I finally got it working with the adb route thank you
The app works great the shortcut works great 
Thank you for the awesome app
I hope it's ok if I can close this as my issue has been fixxed
