### ISSUE TITLE
Praise and ?s for basti564 . . .

### ISSUE THREAD

**Issue by Paulie420** [basti564/Oculess#43]
Thanks so much, basti564 - I've been following your Oculus Quest 2 work for a while and st0ked that I got Oculess running... So far I removed my accounts, ran adb command and enabled background music.
I got my Spotify music (and other apps sound) playing thru my game sessions/other apps. What I *want* to do is play Spotify music so that other PLAYERS can hear. (PokerStarsVR) ... I know this capability is doable using PCVR, but I was hoping that background Spotify would bleed thru... it does not. 
Is there any wizardry we could work for that? Specifically I want background Spofify music to be heard by all users at my PokerStars VR table. Any ideas? 

Thank you so much for Oculess - I'm researching turning off telemetry and POSSIBLY NULLing my FB account - can I turn off telemetry and still have my FB accounts active safely? Very much appreciate this project and thank you kindly, r0ckstar!!!!!

pAULIE42o
. . . . . . . . . . . 
/s

**Comment by threethan** [comment]
I know this is a very old request, and partially sarcastic, but audio routing may actually be possible, I'll look into it when I have time. 
Unfortunately full account or telemetry removal is no longer possible, but it is "safe"

**Comment by ooTruffle** [comment]
As a side note

If you join a discord call through ocolus browser it will keep playing when ingames and get mic audio untill it does a thing

Im also assumeing same with yt / spotify web
