### ISSUE TITLE
[Feature Request] Allow for users to specify their own background and startup apps

### ISSUE THREAD

**Issue by Brickmaster1** [basti564/Oculess#44]
A feature I have really been wanting is custom startup apps (like Discord) so it could show you notifications and have them run in the background, I know it already enables for background audio and stuff (love using Spotify with this) Now all we need is some sort of multimedia overlay (for skipping songs, leaving calls, accepting incomming calls, etc)

**Comment by Rexogamer** [comment]
Just out of curiosity, why has this been marked as wontfix?

**Comment by Brickmaster1** [comment]
I would also like to know this, would it be done in another project, or is there some other reason it wouldn't be possible, I'd just like to know why. Anyways really cool apps really love them.

**Comment by basti564** [comment]
There are three reasons.
1. It doesn't fit the project, Oculess is mainly for removing restrictions.
2. It would require a lot of research and I'm currently not even sure if it's even possible.
3. So far Meta has patched all methods to create overlays over other apps, releasing a method would just get it patched.

**Comment by Brickmaster1** [comment]
Wouldn't the notifications just be a notification, a built in overlay though?

**Comment by threethan** [comment]
Newer versions let you control media through notifications. However, push notifications (eg. Discord) would require implementing google play services. Starting the app automatically would not do it.

The Oculus shell doesn't seem to support 2D overlays whatsoever.

This is well outside the scope of this project, if at all possible.
