### ISSUE TITLE
No Remove accounts page

### ISSUE THREAD

**Issue by KyoteKy** [basti564/Oculess#47]
I use a Quest 1. I managed to disable the companion server without light mode(took me a while lol). But now I am stuck again. I cannot remove any accounts. When I click the REMOVE ACCOUNTS option in oculess it just opens up my system display settings. After watching the video tutorial I saw that its supposed to pop up an accounts page, but I don't get that. Is there anything I'm doing wrong?

**Comment by HigginDazs** [comment]
I am having the same issue, on version 40, using a Quest 2. Simply brings me to the settings page when I try to click REMOVE ACCOUNTS. Not really useable as it is...

**Comment by SuSaBoi** [comment]
I just bought Oculus Quest 2 and the same happens on brand new device with latest version 40

**Comment by basti564** [comment]
The "REMOVE ACCOUNTS" button should now be working again :)
