### ISSUE TITLE
Disabling Companion Server issue

### ISSUE THREAD

**Issue by petrij98** [basti564/Oculess#57]
Whenever I try to disable the Oculus Companion Server to remove Facebook/Meta server access, the screen turns white and displays the logo in the corner. Eventually, after randomly clicking the screen long enough, I'm able to locate the button but with extreme difficulty.

**Comment by bogatispeed** [comment]
did you solve it

**Comment by devinSpitz** [comment]
same here :)

**Comment by GitEmulate** [comment]
Guys, you have to disable dark mode. Look at the Oculess readme https://github.com/basti564/Oculess/blob/main/README.md

Install the settings shortcut, go to Display and disable dark mode

**Comment by devinSpitz** [comment]
> Guys, you have to disable dark mode. Look at the Oculess readme https://github.com/basti564/Oculess/blob/main/README.md
> 
> Install the settings shortcut, go to Display and disable dark mode

Ah thanks that makes sense i was not sure as this was not in the Video xD But i also was thinking why should it need that that does not make sense xD
