### ISSUE TITLE
[Feature Request] Casting to Server

### ISSUE THREAD

**Issue by mrphilipjoel** [basti564/Oculess#62]
The Quest already has easy casting abilities to browser, or facebook, etc.

But, it would be cool to have the ability to cast the video ANYWHERE.
I would like to capture the video and have it stream to a server, so I can capture it and display it inside other apps.

It would be cool if casting could be on by default.

**Comment by basti564** [comment]
Hi @mrphilipjoel,
the Quest should already allow you to do that/there are no restrictions in place on casting, so implementing this in Oculess is a bit out of scope, but you can use any existing screen casting app for Android instead and it should work.
I for example share my screen with Discord screen sharing in the Discord Android app and it works great for me.

**Comment by JosvanderWesthuizen** [comment]
> The Quest already has easy casting abilities to browser, or facebook, etc.
> 
> But, it would be cool to have the ability to cast the video ANYWHERE. I would like to capture the video and have it stream to a server, so I can capture it and display it inside other apps.
> 
> It would be cool if casting could be on by default.

@mrphilipjoel did you end up finding a good solution for this?
