### ISSUE TITLE
if you had multiple accounts and doesn't work i got a fix. SCRATCH THAT!

### ISSUE THREAD

**Issue by MissandeiVR** [basti564/Oculess#64]
I can no longer prove this works. as i tried it again after factory resetting my device! and after changing my name and restarting the app. it still did not change the owner. perhaps i enabled oculuss in the permissions as well as companion. but if my guide works for you i am happy i could help. please if this does not work for you please let me know. If you multiple accounts. the command doesn't work but i have messed around in the settings and found out there is just a way to completely get around the command. just go into settings with remove account and navigate to system/advanced/multiple users. and click. on your own name and edit it to oculuss. restart device and it should work as if you changed the owner to oculuss

**Comment by MegumiMizu** [comment]
Thanks for reading. and i hope this helps people having issues with the command.

**Comment by MegumiMizu** [comment]
@basti564 i seen an app called Q4BService in device admin apps. is this oculus/facebook app? should i not enable it or it doesn't matter?

**Comment by MegumiMizu** [comment]
it worked for me this time. i was able to remove both facebook and oculus from the users. last time i was having an issue with them not being able to be removed. they remove then in a few seconds go back. i was able to quickly remove them and run the command. but very tricky.

**Comment by basti564** [comment]
> it worked for me this time. i was able to remove both facebook and oculus from the users. last time i was having an issue with them not being able to be removed. they remove then in a few seconds go back. i was able to quickly remove them and run the command. but very tricky.

Interesting, I will see if I get it to work and add it to the Readme.md if it does

**Comment by OneMcPlayer** [comment]
> If you multiple accounts. the command doesn't work but i have messed around in the settings and found out there is just a way to completely get around the command. just go into settings with remove account and navigate to system/advanced/multiple users. and click. on your own name and edit it to oculuss. restart device and it should work as if you changed the owner to oculuss

Since the last time when I added oculess as the owner of the device, it blocked me from adding a new secondary account (the account section did not show up as if the primary account was also a secondary account).
Today I tried this new method with the latest version of the OS on the Quest 2 and it doesn't seem to work. Maybe I should try renaming the account oculess instead of oculuss for another try? ([Video of my attempt](https://drive.google.com/file/d/1hrp6iCKGFSWX87-588sPybUmoCshEGCS/view?usp=share_link))

**Comment by threethan** [comment]
I did some testing, and found a different method that seems to work as of v56. Hopefully this stays true. Check the readme for details
