### ISSUE TITLE
[Question] Any chance that this (or similar) will work to free Rift / Rift S headsets from the Meta requirement?

### ISSUE THREAD

**Issue by imhere-gh** [basti564/Oculess#65]
[Apologies if this is the wrong place.]
Just wanted to inquire if this or other methods also work for wired headsets requiring Meta accounts. People are already getting their devices bricked over Meta being wonky, plus the 2023 deadline is quickly approaching. If anyone knows of a way that works (or is in the works) that can get around this issue I and many others would be much obliged. 

I didn't find a discord or similar so thought this would be the place to ask. Also new to Github so apologies for formatting. 

Thanks!

**Comment by basti564** [comment]
Hi @imhere-gh,
I'm not familiar with how the Rift / Rift S login works, so I can't help you with that.
There is a [Discord](https://discord.gg/3PhN9tvg7j), but I don't think anyone else has looked into it yet..

[I'm closing this issue as this is unrelated to Oculess]
