### ISSUE TITLE
Audio and latancy issue

### ISSUE THREAD

**Issue by MiMillieuh** [basti564/Oculess#66]
Hello,

I have some issue when using Oculess audio in background : 
I'm usually using it with discord to talk with my friends while playing but sometimes I get huge latancy (over 8 seconds sometimes).
I also sometime have the background audio crashing and have to exit what I was doing to re-enable it.

Also this isn't maybe related to Oculess but the audio on discord it sometimes controlable and sometimes not. 

Thanks for your hard work.

**Comment by basti564** [comment]
It's a Quest / Discord issue, Oculess can't do anything about it

**Comment by MiMillieuh** [comment]
> It's a Quest / Discord issue, Oculess can't do anything about it

Even the background audio being disabled ?
