### ISSUE TITLE
I think oculess made my media sync stop working

### ISSUE THREAD

**Issue by HimmatBajwa** [basti564/Oculess#67]
after using oculess for background audio horizon accounts center doesn't show up in settings and media sync doesn't work.

**Comment by DiplomatPig212** [comment]
> after using oculess for background audio horizon accounts center doesn't show up in settings and media sync doesn't work.

I'm having the same problem. it seems i can't remove oculess from my headset either, and I can't get a lot of meta account functionality back, like messages and media sync.

**Comment by kskillins** [comment]
Same here. I think it has to do with the remove accounts. Is there a reason we NEED to do this?  We can’t enable background audio or make the quest an owner without doing this?

**Comment by threethan** [comment]
> Same here. I think it has to do with the remove accounts. Is there a reason we NEED to do this? We can’t enable background audio or make the quest an owner without doing this?

Unfortunately, yes. A workaround for re-adding accounts is now in the readme
