### ISSUE TITLE
Discord Screenshare broken with Firmware Update v44

### ISSUE THREAD

**Issue by partyp770** [basti564/Oculess#68]
Discord screenshare is no longer working as of Quest Firmware Update v44, same with skype screenshare, and I'm assuming every other sideloaded application that tries to capture the screen. 

See https://forums.oculusvr.com/t5/Quest-Development/Downgrading-firmware-for-device-management-use/td-p/992199

**Comment by threethan** [comment]
Unfortunately this seems to be a system issue, and wouldn't be fixable without modifying the OS. Unfortunate, but not something this application could fix.
