### ISSUE TITLE
Enable Background Audio feature stoped working for some reason

### ISSUE THREAD

**Issue by hutonahill** [basti564/Oculess#74]
Whenever I close the Oculess app it resets the Enable Background Audio feature. I had this working yesterday, but today when I try to run amazon music and any full oculus store app it closes oculess and amazon music while the application is booting up. I tried re-removing the accounts and re-running the command to Make Oculess a "Device Owner" but it returned an error and didn't help.

**Comment by basti564** [comment]
The latest version now works with newer quest updates :)
