### ISSUE TITLE
Every is disabled, i cant do anything, help

### ISSUE THREAD

**Issue by Fox-of-the-Kin** [basti564/Oculess#75]
![com oculus shellenv-20221221-223604](https://user-images.githubusercontent.com/110227891/209043308-24452e2d-9b88-4924-8dd9-655e8440c7ef.jpg)

**Comment by jakkieblue** [comment]
You need to press "Remove Accounts" and remove them all and you also need to connect to a pc and run the following command in sidequest adb commandline:

adb shell dpm set-device-owner com.bos.oculess/.DevAdminReceiver

have you done both of those things?
