### ISSUE TITLE
Disabling Telemetry breaks Wi-Fi settings (crashing every time going into Wi-Fi)

### ISSUE THREAD

**Issue by DevanWolf** [basti564/Oculess#76]
Caused by v49 update

**Comment by basti564** [comment]
Does enabling telemetry fix it crashing, or does it keep crashing?

**Comment by dsa83** [comment]
Hello, I have the same. After turning on telemetry, Wi-Fi settings return to normal.

**Comment by threethan** [comment]
This seems fixed as of a recent system update
