### ISSUE TITLE
Question: Rolling back to V41 or support for later versions?

### ISSUE THREAD

**Issue by Normand-Nadon** [basti564/Oculess#77]
First of all @basti564, amazing work, thank you!

I delayed the task of putting your patch on my Quest 1, but disabled updates back in V40 or 41...
This morning, I had the displeasure of having a forced Meta update that brought me up to V49 and locked me out of my device unless I create a "/$"$@% Meta Account (spoiler alert: I WON'T!!!)

**Do you know of a safe way to revert to V41** and disable Telemetry and Facebook and whatever Zuk has in mind ?
Or is there a way to remove Telemetry on later versions? I know Oculess can't because Meta made it a service instead.

**Comment by basti564** [comment]
You sadly can't downgrade back to older versions ever since they are based on Android 10.

Blocking updates also hasn't worked ever since around v37 if I recall correctly

**Comment by Normand-Nadon** [comment]
So there is nothing I can do to use Oculess on my headset then? It won't work?... That is sad!
