### ISSUE TITLE
Quest2 - start my app after boot?

### ISSUE THREAD

**Issue by davoodkharmanzar** [basti564/Oculess#8]
hi dear,
does exists any method to start specific apk [i mean app] after boot on quest 2 without using launcher?

thanks a lot.

**Comment by basti564** [comment]
Hello, [this solution](https://stackoverflow.com/a/64433656/9274450) from stackoverflow, it should work on the Quest :)

**Comment by davoodkharmanzar** [comment]
thanks for your reply :]

but seems that **RECEIVE_BOOT_COMPLETED** permission is restricted on quest devices :\
https://developer.oculus.com/distribute/vrc-quest-security-2/

**Comment by basti564** [comment]
> thanks for your reply :]
> 
> 
> 
> but seems that **RECEIVE_BOOT_COMPLETED** permission is restricted on quest devices :\
> 
> https://developer.oculus.com/distribute/vrc-quest-security-2/

Hmm, I thought it was just restricted for store releases. I will let you know if I find another way to accomplish that.

**Comment by davoodkharmanzar** [comment]
> 
> Hmm, I thought it was just restricted for store releases. I will let you know if I find another way to accomplish that.

nice ...
and it would be great if exists some methods to access to these permissions:
**android.permission.BIND_DEVICE_ADMIN
android.permission.DEVICE_POWER
android.permission.SHUTDOWN
android.permission.RECEIVE_BOOT_COMPLETED**
