### ISSUE TITLE
How do I put this in from factory reset

### ISSUE THREAD

**Issue by Anomyous1** [basti564/Oculess#80]
Today after a couple days without use just sitting on a charger my quest went to 94%
when i turned it on it sat pulsing the meta logo for about 2 hours before i reset it several times and eventually factory reset.
but then it asked me for a code.
a code which requires a meta account
an account which i do not have, and obtaining will require me to destroy my occulus account.

I plugged in my quest and downloaded the apk according to https://www.youtube.com/watch?v=PO-XBQHT-Ks
adb shows this:

Oculess>adb devices
List of devices attached

The screen in the quest is just a JPEG saying "input code from meta quest app"
this is really strange because even though i factory reset my """"OCULUS QUEST""" it is requesting ""META"" app access.

so please tell me how I can use my quest!! right now its just a brick!

**Comment by Bluscream** [comment]
You need a meta account anyway.
