### ISSUE TITLE
Oculess guardian issue

### ISSUE THREAD

**Issue by liltrillix** [basti564/Oculess#81]
So ever since I got oculess my guardian has been going on and off mid-games. Also when I tried deleting the app it didn't work.

**Comment by fabJunior** [comment]
I second that, kept having issues with guarding crashing/not responding and being quite weird since I installed oculess :c

**Comment by liltrillix** [comment]
I honestly just wanna know how to uninstall oculess because it's getting to the point as that I feel I need to file a complaint about it to Meta themselves.

**Comment by liltrillix** [comment]
@basti564

**Comment by fabJunior** [comment]
Well, from the README it says that if you did run the command `adb shell dpm set-device-owner com.bos.oculess/.DevAdminReceiver` then you'll have to factory reset if you want to uninstall Oculess

**Comment by GiraffeMan3125** [comment]
im having the same issue and im about to factory reset my headset with how bad this is.

**Comment by TobiPower20** [comment]
yeah i have the same problem. Whenever I install oculess and run the adb command, I always get the error message "guardian keeps stopping" from the guardian. and in a continuous loop, every few minutes

**Comment by haarp** [comment]
Which Quest and firmware version yall on?

**Comment by TobiPower20** [comment]
> 

i have the update version 49. but i wait for the update 50 and hope there is it fix

**Comment by Bl0odlust** [comment]
@haarp @TobiPower20 i made a recent post and replied to someone with same issue as i said his file has become corrupted sideloading it into ur vr corrupts  your boundary i would recommend not using it uninstalling it and wait for a update

**Comment by Bl0odlust** [comment]
oculus updating wont fix it either HE had to fix it the dev not to mention v50 aint supported yet

**Comment by threethan** [comment]
Guardian issues are known to occur if too many apps are running in the background. This has nothing to do with Oculess specifically, and Oculess can now be completely uninstalled without reset.

You may want to clear data for guardian. More info/steps [here](https://communityforums.atmeta.com/t5/Get-Help/Quest-2-losing-tracking-gt-forgetting-guardian-all-the-time/td-p/976885)
