### ISSUE TITLE
[Feature request] Support V54 firmware

### ISSUE THREAD

**Issue by necros2k7** [basti564/Oculess#82]
subj

**Comment by basti564** [comment]
It doesn't support it. v50 breaks a lot of things and it should not be used.

**Comment by TYTheBeast** [comment]
is there any plans to support v50 or update the app in a way that still gives us some of the features, such as background audio? or did Meta effectively kill yet another good project? :/

**Comment by threethan** [comment]
The main issue is that removing the Meta account is permanent.
Oculess doesn't cause this issue, and could not fix it. However, it is required to remove all accounts to set any app as device owner.

**Comment by basti564** [comment]
Yep, removing the meta account is permanent, but not as bad. Tho thanks to @threethan at least background audio works on v54
