### ISSUE TITLE
Games crash

### ISSUE THREAD

**Issue by NotApex** [basti564/Oculess#84]
Everytime I start a game after playing for 5 min my game crashes or I get a popup saying com.oculus.guardian at least add a warning saying its gonna fuck up your quest I'm probably gonna reset

**Comment by Bl0odlust** [comment]
Yep  the oculuss file/apk or whatever is corrupted every time it is sideloaded it begins corrupting ur boundary the only fix in my experience is factory resetting and not adding it back onto ur headset

**Comment by threethan** [comment]
Guardian issues are known to occur if too many apps are running in the background. This has nothing to do with Oculess specifically, and Oculess can now be completely uninstalled without reset.

You may want to clear data for guardian. More info/steps [here](https://communityforums.atmeta.com/t5/Get-Help/Quest-2-losing-tracking-gt-forgetting-guardian-all-the-time/td-p/976885)
