### ISSUE TITLE
Should i factory reset?

### ISSUE THREAD

**Issue by ArranPlayz** [basti564/Oculess#86]
I've been having significant issues with oculess like all the others (I'm on v49) and I'm wondering if you will fix this in an update. If so, should I wait or should I factory reset?

**Comment by Bl0odlust** [comment]
Go ahead and factory reset god only knows when hes gonna update and fix it (oculus update wont fix it especially bc its un supported) if u dont go ahead and  factory reset ur not gonna be able to play at all @ArranPlayz

**Comment by basti564** [comment]
The latest version now works with newer quest updates and allows you to uninstall the app without a factory reset. So no need to do it anymore
