### ISSUE TITLE
V50 support

### ISSUE THREAD

**Issue by machmalpause** [basti564/Oculess#87]
It would be fantastic if Oculess would someday support V50 ... ?
... got so used to this fantastic tool ...
until we can one again disable telemetry and meta accounts I'm afraid my Quest 2 has to stay offline :-(

**Comment by Detla7t** [comment]
although it may not be simple i wait in suspense for the day i can put oculess on my quest 1 v50 and make facebook no more on my headset

**Comment by Zthrowaway** [comment]
@Detla7t @machmalpause basti564 updated the .readme

In big bold letters: **Oculess (DON'T USE V50)**

**Comment by LiderKonmils** [comment]
The only thing we want to know is if it's over forever or if it just need a big update.

**Comment by machmalpause** [comment]
.
