### ISSUE TITLE
Background Audio WORKS in v50

### ISSUE THREAD

**Issue by threethan** [basti564/Oculess#88]
I installed the latest version of Oculess on a factory reset v50 device. I cannot test if this app causes issues when updating to v50, it might.

Attempting to disable telemetry causes issues (not able to modify wifi settings using system or network over LAN)
Disabling updated and logging out of accounts permanently have been broken for longer.

However, **enabling background audio playback still works flawlessly,** as it did on prior versions. I did not notice any issues when only using that option.

The actual "issue" here is the warnings in the ReadMe and releases. I could make my own fork with just the audio tweak I developed, but that would force factory resets to switch between versions. (You can't update an app with a different signature)

**Comment by basti564** [comment]
Yes, background audio works on v50, but the step prior to setting the app as device owner, deleting accounts, seems to be permanent with the change to meta accounts and breaks some functionality

**Comment by Silent-Hunter** [comment]
What functionality does it break? My boyfriend needs this to be able to play Walkabout Mini Golf and use Mumble for our voice chat, but he also uses AirLink. Does this break AirLink?

**Comment by threethan** [comment]
I can confirm air link works.

**Comment by basti564** [comment]
I think it was some functionality related to chats and sharing options

**Comment by nvram93** [comment]
so, what's the current state of background audio for someone who never used Oculess?
Is it possible to enable it or does the app need to be device owner (which isn't possible anymore)

**Comment by threethan** [comment]
I got it working and was getting ready to make a PR. (The issue was with
some things that worked on Android 10 but not Android 12, fairly simple
fix) But - it seems like Facebook might just be pushing out background
audio officially?

It's been available on Quest Pro for a while and I just got it on my Quest
2 under experimental settings.

I could still push my update. I improved my own hacky implementation a
bunch. However, missing a meta account has gotten worse the was few
updates. Now it locks out all recording/casting features now. Honestly
don't see why it would be worth it when an official solution is on the way.

Sidenote: I managed to get the Quest to re-add the removed meta account
once, but haven't been able to replicate that.

**Comment by basti564** [comment]
> Honestly don't see why it would be worth it when an official solution is on the way.

I agree, now that it's an official feature and the other features have been broken I'm considering to archive the repo

**Comment by Silent-Hunter** [comment]
Is it an official feature in Quest 1? I only have Quest 1.

**Comment by threethan** [comment]
No idea. It wasn't announced outside of the quest pro. I think I'll push my PR later today, along with an in app warning about the meta account thing.

**Comment by threethan** [comment]
Check #94 for fix.

I'll leave this thread open for discussion regardless, though @basti564 is welcome to close it.
