### ISSUE TITLE
Oculess

### ISSUE THREAD

**Issue by mh82** [basti564/Oculess#91]
Hello,

I see since yesterday Oculess not anymore in Unknown Sources but now it's under Company Managed. My issue is that since that time Spotify will not play in the background. I enable background audio like always worked before. Is it not working anymore due to an update of Meta or is there something I must know in order to fix this issue? I'm looking really for a solution since I use Oculess on a daily base so thank you very much.

Mark

**Comment by Pinokjappa** [comment]
I seem to be having the exact same issues, did u find a solution?

**Comment by GateteFachero** [comment]
The same thing happens to me, if you find a solution let me know

**Comment by mh82** [comment]
Since updated to 5.1 functionality has been broken. Basti told to have maybe an alternative solution. I have no clear timepad of this when we can test of it's gonna work.

**Comment by GateteFachero** [comment]
Ok

**Comment by 007Masters** [comment]
i read that the only way to get rid of oculess is by doing a factory reset but i think that if we find the user folder, or just an adb command to remove the organization, we can get rid of it, i think that we cant uninstall it because it is the admin
tell me if someone found one of these 2 thing

**Comment by basti564** [comment]
Yep, the only way to uninstall this is a factory reset. It also looks like Meta is adding background audio to the quest 2 (check experimental settings) The Quest Pro had it for ages.

**Comment by koentjeappel** [comment]
> Yep, the only way to uninstall this is a factory reset. It also looks like Meta is adding background audio to the quest 2 (check experimental settings) The Quest Pro had it for ages.

That would be amazing if it will become standard, my friends dont play VR and i just like to sit in discord while i play. I don't understand why that functionality is not there already.

**Comment by 007Masters** [comment]
They are working on it and now that v51 is almost out we need to wait a
little more

**Comment by threethan** [comment]
Background audio has been fixed by #94 . It was broken by the update to from Android 10 to 12 rather than an intentional move by Facebook.

However, official background audio is rolling out to Quest 2, and the missing Meta account problem is a growing issue.
