### ISSUE TITLE
Quickly reply! Used on v50

### ISSUE THREAD

**Issue by HussLegends** [basti564/Oculess#92]
I used oculess on v50 and it was working fine I guess, I was just using it for spotify because I couldn't be bothered to keep going on another device with the meta quest browser, but then I decided to turn off auto update because I remembered that it said that this doesn't work on v50, so now I am on v51 but first I noticed in settings it said that my devices is controllers and supervised by my administrator and when I went to accounts, it said that I cant add a new account because it's controlled by my administrator. I tried looking for oculess again because I realised this was oculess glitching but oculess was removed from my headset, I am going to try and reinstall is now and try some things but please could you help me fix this.

**Comment by basti564** [comment]
The only way to uninstall this is a factory reset (It doesn't work on the latest update). It also looks like Meta is adding background audio to the quest 2 (check experimental settings) The Quest Pro had it for ages so it isn't worth it to fix it.

**Comment by basti564** [comment]
The latest version now works with newer quest updates and allows you to uninstall the app without a factory reset. So no need to do it anymore
