### ISSUE TITLE
Command: adb shell dpm set-device-owner com.bos.oculess/.DevAdminReceiver not working

### ISSUE THREAD

**Issue by IP1ayGam3** [basti564/Oculess#95]
Using the command adb shell dpm set-device-owner com.bos.oculess/.DevAdminReceiver doesn't work even after revooting or deleteing apps with accounts

**Comment by IP1ayGam3** [comment]
![image](https://github.com/basti564/Oculess/assets/134235396/0dbf4181-0c4c-4888-8816-ee16bae60be2)

**Comment by threethan** [comment]
Is Oculess installed?

**Comment by IP1ayGam3** [comment]
May you forgive my foolishness, because for some reason it wasn't. My bad. I don't know why I missed that step...
