### ISSUE TITLE
Oculess not showing in app menu

### ISSUE THREAD

**Issue by MiMillieuh** [basti564/Oculess#96]
Hello,

Since the update to 1.40 I don't have the application showing in the unknown source tab on my oculus quest2

However I can launch it from ADB with sidequest on my laptop.

Is there any fix for this issue ? 

Thanks.

**Comment by MiMillieuh** [comment]
Fixed by a factory reset... 

Still wondering why it wasn't in the app menu but I can launch it with sidequest...

**Comment by basti564** [comment]
The reason for this is that It shows in "Managed Apps" or whatever it's called.
