### ISSUE TITLE
Observation: Oculus Companion Server re-activates whenever it feels like it

### ISSUE THREAD

**Issue by MeowcaTheoRange** [basti564/Oculess#97]
Hi! I'm a privacy-concerned Quest 2 user, and I have found that the Oculus Companion Server does not *just* re-enable its own admin every restart -- it also does it whenever you **delete your Facebook and Oculus accounts from the device**, whenever you **put the device into sleep mode**, and whenever you **threaten to uninstall it using a sideloaded uninstaller application**.
Just an observation I thought I would tell you!

**Comment by basti564** [comment]
This issue has been identified in recent versions. Oculess's privacy features are only effective in older versions. In the newer versions, these features are limited to enabling background audio and blocking updates.

**Comment by threethan** [comment]
I updated the readme to reflect this.
