### ISSUE TITLE
V1.40 says to enable owner, but it’s already owner

### ISSUE THREAD

**Issue by Echo2660** [basti564/Oculess#98]
When I press the enable background audio it tells me to give it owner or if I have previously to restart my headset, but upon doing so it gives the same message. Any fix?

**Comment by threethan** [comment]
Read the message. Once you have enabled device owner and restarted the headset, background audio will be automatically applied. The message indicates this and will not change.

**Comment by Echo2660** [comment]
Background audio is still not enabled regardless of what the messages says.
